# ===================================
# SonarQube — Projet DevOpsCorp
# ===================================

sonar.projectKey=devopscorp
sonar.projectName=DevOpsCorp
sonar.projectVersion=1.0.4

sonar.host.url=http://localhost:9000

sonar.sources=frontend/src,product-api,auth-api/src

# ── Exclusions ──────────────────────────────────────────────────────────────
sonar.exclusions=\
  **/node_modules/**,\
  **/vendor/**,\
  **/__pycache__/**,\
  **/*.pyc,\
  **/coverage/**,\
  **/dist/**,\
  **/.pytest_cache/**,\
  frontend/node_modules/**,\
  **/__tests__/**,\
  **/tests/**

# ── Tests ────────────────────────────────────────────────────────────────────
sonar.tests=frontend/src/__tests__,product-api/tests,auth-api/tests

# ── Encodage ─────────────────────────────────────────────────────────────────
sonar.sourceEncoding=UTF-8

# ── Python ───────────────────────────────────────────────────────────────────
sonar.python.version=3.11

# ── PHP ──────────────────────────────────────────────────────────────────────
sonar.php.version=8.1

# ── JavaScript/TypeScript ────────────────────────────────────────────────────
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

# ── Python ───────────────────────────────────────────────────────────────────
sonar.python.coverage.reportPaths=product-api/coverage.xml
